version: "3.5"

services:
  rethinkdb:
    image: rethinkdb:2.3.6
    container_name: rethinkdb
    restart: always
    ports:
      - "28015:28015"
      - "29015:29015"
      - "8080:8080"
    command: rethinkdb --bind all --initial-password 1

  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: on-failure
    environment:
      - REDIS_PASSWORD=1
    volumes:
      - redis-data:/data

  bot:
    build: .
    restart: always
    container_name: bot
    environment:
      - RELEASE=LOCAL
      - SHARDS_PER_CLUSTER=1
      - SHARD_COUNT=1
      - HOSTNAME=bot-0
      - TOKEN=abc123
      - RETHINKDB_PASSWORD=1
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=28015
      - RETHINKDB_DB=bloxlink
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1
      - TRELLO_KEY=1
      - TRELLO_TOKEN=1
    volumes:
      - /usr/src/rewrite
    depends_on:
      - rethinkdb
      - redis

volumes:
  redis-data:
